### ISSUE TITLE
Response code of 401 when making GET request

### ISSUE THREAD

**Issue by dylan-turner25** [FirstStreet/fsf_api_access_python#11]
**Question:**
Accessing the API via the python client works fine. However, when making a GET request in python, a response code of 401 is returned. The following code produces the 401 response code.

`import requests
url = "https://api.firststreet.org/apikey/v1/check"

header = {
  "Authorization": "Bearer api-key"
}

r = requests.get(url, headers=header)
print(r)
`
**Additional Information:**
Python Version: 3.7.4

Fsf-api-access-python Version: 1.3.1

**Comment by Lyetenth** [comment]
Hey Dylan, 

A 401 response error is an authorization due to an invalid API key. Did you replace the api-key placeholder with the API key?

It also looks like the documentation on the Authorization page is outdated. Try the code snippet below replacing the API key:

```
import requests
url = "https://api.firststreet.org/v1/apikey"

header = {
    "Authorization": "Bearer iaq02n0rsserdxgnyf3vdrp93aqti393"
}

r = requests.get(url, headers=header)
print(r.json())
```

**Comment by Lyetenth** [comment]
Hey Dylan,

A 401 response error is an authorization due to an invalid API key. Did you replace the api-key placeholder with the API key?

It also looks like the documentation on the Authorization page is outdated for the endpoint. Try the code snippet below replacing the API key:

```import requests
url = "https://api.firststreet.org/v1/apikey"

header = {
    "Authorization": "Bearer YOUR-API-KEY"
}

r = requests.get(url, headers=header)
print(r.json())
```

**Comment by dylan-turner25** [comment]
Replacing the API placeholder with my own API key returned a 401 response error for the code that was  in the authorization documentation. The code snippet you provided works fine though, Thanks!
