### ISSUE TITLE
Importing maptiles directly in ArcGIS

### ISSUE THREAD

**Issue by pranjalirai** [FirstStreet/fsf_api_access_python#14]
Is there a way to directly import map tiles through the First Street Foundation API in ArcGIS?

There is a way to add web data in ArcGIS online. But, it is not working for First Street Foundation API. The request results in an empty layer. Following is a screenshot of my request in ArcGIS online:
![maptile_ArcGIS](https://user-images.githubusercontent.com/57599303/88718732-12ca1100-d0d7-11ea-80f3-2c3d774ed18e.PNG)

Currently, I have to download the tiles as PNG files and manually georeference it in ArcGIS, which is very cumbersome and not precise. 

I will appreciate any help or reference for solving this issue.
Thanks

**Comment by seripap** [comment]
Try this as the `URL`:

```
https://api.firststreet.org/v1/tile/probability/depth/2020/5/{level}/{col}/{row}.png?key=<replace with your api key>
```

the `2020` and `5` fields are interchangeable for year and return period.

**Comment by pranjalirai** [comment]
I tried to import using the interchanged url.
It is still not working. It produces an empty layer
Are you familiar with any other method of importing the tiles in ArcGIS?

**Comment by seripap** [comment]
I've used the example URL provided above and imported it as a tile layer and everything seems to be working as intended:

<img width="1129" alt="Screen Shot 2020-07-29 at 12 10 19 AM" src="https://user-images.githubusercontent.com/683200/88755865-16d64d00-d130-11ea-8b0e-2ee4124f849e.png">


<img width="1072" alt="Screen Shot 2020-07-29 at 12 08 44 AM" src="https://user-images.githubusercontent.com/683200/88755676-ae876b80-d12f-11ea-8fab-c93e823b62f8.png">

**Comment by pranjalirai** [comment]
Thanks for the screenshots.

I misunderstood your instructions in the previous message.

I am able to import now 👍

**Comment by pranjalirai** [comment]
One last question.
I tried the same link to import maptiles in ArcGIS Pro. But, it did not work.
![ArcGIS_Pro](https://user-images.githubusercontent.com/57599303/88760807-aa088600-d122-11ea-83e5-e53b0fcb426f.PNG)
![ArcGIS_Pro_error](https://user-images.githubusercontent.com/57599303/88760815-ad037680-d122-11ea-8d83-27887dda2dce.PNG)
Can you help me with the link I should use in ArcGIS Pro?
Following is the documentation. Please look for "Add a dataset from a path"
https://pro.arcgis.com/en/pro-app/help/mapping/layer-properties/add-layers-to-a-map.htm#ESRI_SECTION1_FABB01A75AFE4A1FB0BEC3D7CE74E3C5

**Comment by seripap** [comment]
Sorry I am unaware of ArcGIS Pro, however the method should remain the same, the same URL could be used to show the flood maps. The only thing you have to replace is your API key itself. You can also test this URL:

```
https://api.firststreet.org/v1/tile/probability/depth/2020/5/{z}/{x}/{y}.png?key=<replace with your api key>

```

**Comment by pranjalirai** [comment]
No problem.
I am getting the same error for both urls. Following are the snapshots:
![ArcGIS_Pro_error_old_key](https://user-images.githubusercontent.com/57599303/88843446-fb9e2880-d195-11ea-83ee-e0e5fe546b76.PNG)
![ArcGIS_Pro_error_new_key](https://user-images.githubusercontent.com/57599303/88843455-00fb7300-d196-11ea-9fe5-558632292ac2.PNG)

But, I was able to import the ArcGIS Online webmap into the desktop application (ArcGIS  Pro).
This helps me to view the FSF layers in the Desktop application.
However, to be able to analyse the raster layers using ArcGIS tools I still need to download and georeference the tiles.
This takes a long time as I am doing a statewide analysis. 

Do you have any suggestions to speed up the process? 

Thanks for your time and patience.

**Comment by seripap** [comment]
Sorry I am unfamiliar with ArcGIS pro and would not be able to assist. @fitnr would you have any knowledge on how to overlay our tiles through a baseurl through ArcGIS pro?

**Comment by fitnr** [comment]
I can confirm that adding the tile layer works in ArcGIS Online but not ArcGIS Pro 2.2.4. It may work in a later version of Pro. I can confirm the layers work in QGIS.

>  However, to be able to analyse the raster layers using ArcGIS tools I still need to download and georeference the tiles.

The raster data in the tile API is only appropriate for display, not analysis. The images contains the four colors in our display style.

**Comment by pranjalirai** [comment]
Thanks for the clarification Neil.
Is there a way to speed up the tile download?

**Comment by fitnr** [comment]
Sorry, the Tiles API is designed for display, not for download.

**Comment by Lyetenth** [comment]
Hey Jeremy @jrp1113, the issue

**Comment by jrp1113** [comment]
@pranjalirai please reach out to me and Brett Lingle directly at jeremy@firststreet.org and brett@firststreet.org.  We have some abilities to share tiles directly for Flood Lab members given the data use agreements.

**Comment by pranjalirai** [comment]
That is really helpful.
We are in the process of figuring out the zoom level that we need for our analysis.
Once we decide, I will be in touch.
Thanks
