### ISSUE TITLE
Error 500 on get_depth for some coordinates

### ISSUE THREAD

**Issue by mulderphilip** [FirstStreet/fsf_api_access_python#15]
I am trying to pull depth data for a large number of coordinates that correspond to property parcel centroids in another dataset which I am feeding into the API in smaller lists. What I've found is that there are a small number of coordinates that cause an entire pull command to stop and return 'InternalError: Network Error 500: Could not be found' if they are included in the list. To give a sense of the problem's scale, in going through my first ~450 coordinates I have found two that cause pulls to break. 

There are other coordinates where I receive a N/A value. I assume that this is because the underlying property is not covered in the model for whatever reason. So, this appears to be some kind of distinct issue that causes the pull to break. 

Attached are screenshots from my Jupyter Notebook session showing several pulls that do work and then a pull with one of the coordinates that causes it break. I am happy to follow up with code, more info, or try checks. Here are the two offending coordinates I've found so far:  [(36.097706045, -79.47390571549998), (36.5271207443, -81.33564109539999)]

Thank you for your help!
![firststreet1](https://user-images.githubusercontent.com/17860784/89205793-464ce580-d586-11ea-9db7-f01fb0290f67.PNG)
![firststreet2](https://user-images.githubusercontent.com/17860784/89205814-4baa3000-d586-11ea-9c9b-f4bb2bf67636.PNG)

**Comment by Lyetenth** [comment]
Hey mulderphilip,

That's a known issue and in the upcoming release it should handle the error to not crash the whole process. There will also be an update to the CSV such that you can differentiate between bad inputs / no property found, and no data (N/A) for the property.

This fix should be up later this week

**Comment by mulderphilip** [comment]
Thank you!
