### ISSUE TITLE
Coordinates that return N/A for depths

### ISSUE THREAD

**Issue by mulderphilip** [FirstStreet/fsf_api_access_python#16]
Using the get_depth command, I notice that some coordinates return "N/A" values. This has come up with about 1% of coordinates in the dataset I've been working with, which are coordinates from a set of property centroids. I assume this means the underlying property isn't in the model. 

Is it possible to run the subset of coordinates returning N/A manually over the flood risk GIS layers to get depths? Is it helpful if I have shapefiles for the underlying properties? Happy to provide more info as needed. 

Thank you!

**Comment by Lyetenth** [comment]
Hi Philip,

Generally, N/A indicates that there is no flood in that area. If you want to send a subset of coordinates to us, we can double check for you.  Please reach out to @jrp1113  (jeremy@firststreet.org) and Brett (brett@firststreet.org) with the subset.

**Comment by mulderphilip** [comment]
Hi Kelvin, 

Thank you for the reply. Just to clarify, N/A means the model predicts "zero" risk of flood at any depth for that location? 

Thanks,
Philip

**Comment by Lyetenth** [comment]
Hi Philip,

I took a look and the only depths that would display N/A -should- only be the ones where the coordinate or FSID failed to match a FSF property. If you get the chance, can you update to the 2.0.0 version and try running the process again? Any depth that has N/A should also show `False` in the `valid_id` column.

Alternatively, if you have a coordinate with N/A, post the coordinate that you tested and I can take a look at if it's an N/A from an invalid id or something else.

**Comment by Lyetenth** [comment]
Closed for inactivity. Please reopen if there are any issues.
