### ISSUE TITLE
API SSL Handshake Failure

### ISSUE THREAD

**Issue by jmorrislev** [FirstStreet/fsf_api_access_python#20]
Basic question here: I am having trouble accessing the API. Running some of the examples from the API documentation, I get an error: "SSL handshake failed on verifying the certificate protocol", with further readouts that may or not be useful.

When I run the first example, probability = fs.probability.get_count(fsids, "tract", csv=True), I get the error above, though the script runs. The result is a CSV pictured below.
<img width="480" alt="fs_csv" src="https://user-images.githubusercontent.com/35849049/89914690-fb048980-dbba-11ea-8979-c2393424635d.png">

Thanks for your help with this hopefully simple issue.

**Comment by Lyetenth** [comment]
Hey jmorrislev,

Are you able to access the api directly from your browser? 

Try accessing this replacing the key with your own:
(https://api.firststreet.org/v1/location/detail/property?lng=-73.9839144787616&lat=40.70307301465067&key=YOUR-KEY-HERE)

**Comment by jmorrislev** [comment]
Yes, that worked. The query returns: `{"fsid":362104205,"streetNumber":"255",...'

**Comment by Lyetenth** [comment]
Hmm okay, so you can access the endpoint directly, but using fsf_api_access_python still doesn't work.

Could you post your python version and a screenshot running `pip list` (activating your virtual environment if you used one)?

**Comment by jmorrislev** [comment]
I am running Python 3.6. I'm using PyCharm, below is the list of packages for this project. Let me know if that's not what you were looking for.
<img width="784" alt="packages" src="https://user-images.githubusercontent.com/35849049/90063042-5bc0be80-dcae-11ea-970e-d211ca2edc25.png">

**Comment by Lyetenth** [comment]
aiohttp looks up to date... Can you try running it again and post the full error here? Also, are you using a private network that may be blocking connections? (Further note that if you upgrade `fsf-api-access-python` to 2.0.0, you'll need to upgrade your Python to 3.7+)

**Comment by jmorrislev** [comment]
Thanks for those suggestions. I updated to Python 3.7 and confirmed that I'm running fsf-api v 2.0.0. I am not using a private network. Here is the full text of the error. I note that the target web address ends in ?None, which seems fishy.


  0%|          | 0/1 [00:00<?, ?it/s]2020-08-13 09:37:08,383 root         ERROR    <class 'aiohttp.client_exceptions.ClientConnectorCertificateError'> error while getting item: 39035103400 from https://api.firststreet.org/v1/probability/count/tract/39035103400?None
100%|██████████| 1/1 [00:00<00:00,  4.97it/s]
2020-08-13 09:37:08,404 root         INFO     CSV generated to '.../data_csv/2020_08_13_09_37_08_probability_count_tract.csv'.
2020-08-13 09:37:08,405 root         INFO     Probability Count Data Ready.

Process finished with exit code 0

**Comment by seripap** [comment]
This error suggests a root certificate has expired. Assuming you are on windows, can you do the following :

1. Go to start, type internet explorer. Run as admin.
2. Go do https://api.firststreet.org click on the padlock icon.
3. Click view certificates
4. Click install certificates, choose either user or local machine.
5. Click Place all certificates in the following store
6. Choose Trusted Root Certification Authorities

**Comment by jmorrislev** [comment]
Hi Daniel. I'm actually using Mac. Could you provide instructions for that please?

**Comment by seripap** [comment]
Unfortunately,  I don't believe it's that simple for the Mac. Let me take this back internally and get back to you to see if we can figure out a work-around.

**Comment by Lyetenth** [comment]
Hey @jmorrislev,

I just pushed a new update (v2.0.1) that will use an updated certificate. Can you update your `fsf-api-access-python` to version 2.0.1, and see if that fixes your issue?

**Comment by jmorrislev** [comment]
Success! Thank you both for your help. - Josh

**Comment by seripap** [comment]
👍
