### ISSUE TITLE
Reading map tiles for Probability Depth

### ISSUE THREAD

**Issue by pranjalirai** [FirstStreet/fsf_api_access_python#21]
What do the cells with RGBA  values: 148-224-235-255 and 148-224-235-0 represent in terms of flood depth?

When I import map tiles in ArcGIS Pro and specify an RGB Alpha Band as Band 4 in Raster Symbology (to make the background transparent), I get 2 types of cells with R (Red) value = 148. These cells have the following RGBA  values: 148-224-235-255 and 148-224-235-0. What is the difference in terms of the flood depth for these cells?

The map documentation on the website do not cover the Alpha values. Also, when I import the map tiles the R=148 cells are white/ transparent in color not Blue #94E0EB as mentioned in documentation on your website https://docs.firststreet.dev/docs/tiles-introduction . Below are some screenshots for your reference.

![RGBA1](https://user-images.githubusercontent.com/57599303/89958251-4a17e200-dbee-11ea-872e-1da0e29de23d.PNG)
![RGBA2](https://user-images.githubusercontent.com/57599303/89958255-4b490f00-dbee-11ea-8b75-a87d1501500e.PNG)

**Comment by jrp1113** [comment]
@seripap this looks like an API export issue.  Do you have any idea how to answer this question above?

**Comment by seripap** [comment]
Could you provide the lat/lng of the area above and scenario for us to debug?

**Comment by pranjalirai** [comment]
I think that the problem occurs when I import the downloaded tile image in ArcGIS Pro. Following  is a description of my process with tile coordinates:

I am doing an analysis for Washington state. Currently, I am testing my method for Snohomish County WA. My process involves downloading multiple map tiles, pasting them together to form one big image, importing the image as raster layer in ArcGIS Pro, and then georeferencing the raster. 

To make things simple, for this issue, I downloaded one map tile in Snohomish County WA with google tile coordinates  (2633,5694) at zoom 14. Following is a snapshot from maptiler.com
![RGBA3](https://user-images.githubusercontent.com/57599303/90171389-48692e00-dd56-11ea-84bf-c81d7fd21525.PNG)

 Below is the saved tile image. In this image there are 5 colors of flood depth visible as per your website documentation https://docs.firststreet.dev/docs/tiles-introduction.
![RGBA4](https://user-images.githubusercontent.com/57599303/90171556-85cdbb80-dd56-11ea-876f-58305f513c74.PNG)

But, when I import this image in ArcGIS Pro to run my analysis, there are only 4 colors visible, and the white portion has RGB values = 148,224,235. Below is the snapshot. 
![RGBA5](https://user-images.githubusercontent.com/57599303/90173028-a7c83d80-dd58-11ea-8726-e348b2d664cf.PNG)

The areas where #94E0EB color appears in the downloaded tile (previous image) has Alpha value = 255. The rest of the white portion (background in the downloaded image) has Alpha value = 0. Below is a snapshot for your reference:
![RGBA6](https://user-images.githubusercontent.com/57599303/90172595-1bb61600-dd58-11ea-8276-b6ef9bd0ffab.PNG)
![RGBA7](https://user-images.githubusercontent.com/57599303/90172679-37b9b780-dd58-11ea-834d-5836df8fb95e.PNG)

**Is there a way to fix this issue?**

**Comment by Lyetenth** [comment]
Hey Pranj,

I've been taking a look into this issue, let me know if this solves your issue.

--

Downloading the same tile coordinate as you have here (with slightly different year and rp):
`fs.tile.get_probability_depth(year=2050, return_period=500, coordinate=[(14, 2633, 5694)], image=True)`
![2020_08_14_12_45_13_probability_depth_2050_500_(14, 2633, 5694)](https://user-images.githubusercontent.com/20485546/90275942-18428d80-de31-11ea-9610-7108a1b1c3ff.png)


I imported the image to ArcMap Desktop (Version 10.8). 

Next:
Under the `Layer Properties` -> Stretch, I set `Type` to `None`
Under the `Layer Properties` -> Stretch, I unchecked `Apply Gamma Stretch`

Ref Images below. You'll see that the missing colour re-appears after I set those two properties.

Please try adjusting those two properties for the image layer, and see if that resolves your issue.

![mstsc_BfQs0MPero](https://user-images.githubusercontent.com/20485546/90276399-d7974400-de31-11ea-812a-d389e807c380.png)
![mstsc_tYSeEb6vvl](https://user-images.githubusercontent.com/20485546/90276430-e3830600-de31-11ea-877c-ed12c01f3258.png)

**Comment by pranjalirai** [comment]
Thanks Kelvin,
The color did appear after applying the settings you mentioned. Following is a screenshot
![RGBA8](https://user-images.githubusercontent.com/57599303/90283864-d233fc80-de25-11ea-9d5c-6a0a8d18e766.PNG)

However, I need the background to have a different R value than the <0.5 ft flood depth color for area and population analysis. For now both the background and #94E0EB color cells have R value = 148. I will look for some options to reclassify in ArcGIS. Let me know if you know any method to achieve that. 

Thanks again!
