### ISSUE TITLE
Potential speed up in FS object list to data frame

### ISSUE THREAD

**Issue by abpoll** [FirstStreet/fsf_api_access_python#27]
For fips 25007, I took the FS API code for taking a list of FS objects and transforming into a data frame as follows 

(Note that fsids is a list of FSIDs for fips 25007)

```
# Extract depths from API
depths = fs.probability.get_depth(fsids)

df = pd.DataFrame([vars(o) for o in depths]).explode('depth').reset_index(drop=True)
if not df['depth'].isna().values.all():
    df = pd.concat([df.drop(['depth'], axis=1), df['depth'].apply(pd.Series)], axis=1)
    df = df.explode('data').reset_index(drop=True)
    df = pd.concat([df.drop(['data'], axis=1), df['data'].apply(pd.Series)], axis=1)
    df = pd.concat([df.drop(['data'], axis=1), df['data'].apply(pd.Series)], axis=1)
    df['fsid'] = df['fsid'].apply(str)
    df['year'] = df['year'].astype('Int64').apply(str)
    df['returnPeriod'] = df['returnPeriod'].astype('Int64').apply(str)
    df['low'] = df['low'].astype('Int64').apply(str)
    df['mid'] = df['mid'].astype('Int64').apply(str)
    df['high'] = df['high'].astype('Int64').apply(str)
else:
    df['fsid'] = df['fsid'].apply(str)
    df.drop(['depth'], axis=1, inplace=True)
    df['year'] = pd.NA
    df['returnPeriod'] = pd.NA
    df['low'] = pd.NA
    df['mid'] = pd.NA
    df['high'] = pd.NA

```

CPU times: user 17min 52s, sys: 23.4 s, total: 18min 16s
Wall time: 18min 15s

On our university's computing cluster, I was on a node with 2 fourteen-core 2.4 GHZ Intel® Xeon® Processor E5-2680 v4, 256 GB of memory and 856 GB of disk. 

This took approximately 18 minutes to run (excluding the initial data grab from the API). 

In contrast, by taking advantage of the JSON structure of each FS object, the following code runs in approximately 1 minute and 11 seconds

```
depth_list = list()
# Loop through FS objects
for d in depths:
    # Normalize data to get df
    df_temp = pd.json_normalize(d.depth, 
                                record_path='data',
                                meta='year')
    # Add FSID to row
    df_temp['fsid'] = d.fsid
    # Add rows to df - return periods matched to depths across scenarios
    depth_list.append(df_temp)
# Get into df
# fs_depths = pd.concat(depth_list, axis=0)
temp = pd.concat(depth_list, axis=0)
```
CPU times: user 1min 15s, sys: 1.99 s, total: 1min 17s
Wall time: 1min 17s

The results are identical across resultant data frames (although the FS method converts the depth values to strings). 

Would it be possible to look into whether the writing to csv could be sped up by using the pd.json_normalize method?

**Comment by Lyetenth** [comment]
Hey abpoll, thanks for the details on making the dataframe conversion faster and the sample code! 

I'll definitely take a look into making those changes to the project. That part of the pipeline was always lagging a bit behind, and needed to be written for sure.

**Comment by abpoll** [comment]
Thanks! I don't know what happens when this is run on a request with less or more properties. Hopefully the json_normalize scales well.

**Comment by Lyetenth** [comment]
Hey abpoll,

I added your suggestion to the new release (2.1.0). 

Some stats on the improvements for 1000 FSIDs:

```
Probability Depth
Before: CSV Time: 56.31201934814453 seconds
After: CSV Time: 3.2082200050354004 seconds

Probability Chance
Before: CSV Time: 22.457255363464355 seconds
After: CSV Time: 2.6708309650421143 seconds

Count-Summary
Before: CSV Time: 30.93870973587036 seconds
After: CSV Time: 3.643561840057373 seconds

Count
Before: CSV Time: 133.2593002319336 seconds
After: CSV Time: 8.79573369026184 seconds

Cumulative:
Before: CSV Time: 28.41595959663391 seconds
After: CSV Time: 3.954843759536743 seconds


Running on 20k lat/lngs:
Before: CSV Time: 1310.2146520614624 seconds
After: CSV Time: 68.37068104743958 seconds
```

Thanks again for the suggestions
