### ISSUE TITLE
Which type of flood hazard was modeled for a particular depth?

### ISSUE THREAD

**Issue by abpoll** [FirstStreet/fsf_api_access_python#32]
**Is your feature request related to a problem? Please describe:**
Is it possible to have a field in the location api that indicates whether an inundation at the property level was modeled using the marginal pluvial or fluvial distribution or the joint distribution of these with coastal processes? It seems like this would be a 1:1 FSID:flood_type mapping and could be in the detail api. 

**Describe the solution you'd like:**
If this is possible, it could be a field that generates "pluvial," "fluvial," or "all" as a response. 

**Additional context:**
The detailed methodology provides some guidance over which types of parcels would be modeled under the joint distribution, but it's not possible to replicate and identify with the data made available. The coastal areas seem to closely reflect subwatersheds off the national shoreline, but the detailed methodology states that the joint distribution of hazard is modeled for parcels inundated by a 5000 year flood w/ a 2km additional extent. In order to avoid incorrectly assigning some parcels a "coastal" designation, it would be great to have this field returned in the depth api. 

The county location detail api has the isCoastal field - are coastal areas always larger than a county? It doesn't seem like the way the joint distribution modeling is described in the detailed methodology would guarantee this.

**Comment by Lyetenth** [comment]
Hey @abpoll , 

Thanks for the feature request. We don't have any plans to currently implement this, but we may look back into it at a further date. We'll reopen this at that time.

If there is any other data you may need in the meantime, let us know and we can see if we can get that data for you
