### ISSUE TITLE
Location Detail Elevation Field Appears Incorrect

### ISSUE THREAD

**Issue by mulderphilip** [FirstStreet/fsf_api_access_python#35]
Hello, 

I have been working with the location get detail product and using the returned elevation field over a large set of Miami properties. I've noticed a few odd things about the data that suggest this field may not be currently reporting elevations. 

According to the data dictionary, the elevation units are in centimeters measured by the NAVD88 datum. However, across my ~450000 properties, all of the elevation fields report a value between 1202681 and 1277075 - or around 40,000 feet! A subsample of my data include measurements of property elevation which typically around 10 feet. These measurements are in the NGVD29 datum, but that should only cause a difference of a few feet. 

I've also noticed some patterns in the elevation field which suggest it may be some sort of ID rather than data. First, all of the values start with "12" - Florida's state FIPs code and the same prefix used in the FSIDs. Second, many nearby properties share the same elevation that, although nearby, should probably have elevations that differ by at least a few centimeters in any relatively granular DEM. 

I'm writing to confirm whether the elevation field is reporting the right data and whether any related updates might be in the works.

Below is a Python snippet that pulls three FSIDs for which I have the alternative elevation measures. In my data, the non-First Street elevation measures are 9.82, 9.59, and 12.9 feet respectively. I'm running Python 3.7.9 on Jupyter Notebook, Windows 10. I updated to the latest API access last week. 

Python snippet: 
import shapely.geometry
import nest_asyncio
nest_asyncio.apply()
import numpy as np
import pandas as pd
import requests
import json
import os
import csv
from csv import DictReader
import firststreet
fs = firststreet.FirstStreet("api-key",rate_limit=5000,rate_period=62)

pull_fsid = [1200222863,1200255169,1200255167]
fs.location.get_detail(pull_fsid,'property',csv=True)

**Comment by Lyetenth** [comment]
Hey @mulderphilip ,

You're correct, it looks like the elevation column in the CSV got assigned the city_fips value instead. I've made an update to the library (to 2.2.1) that fixes this issue. You can also see the updated elevation value in the screenshot below which are close to the non-FSF elevation data you have (297, 203, 336).

Please make an update, and check if the fix resolves the bug

![EXCEL_1f3MmPgPVG](https://user-images.githubusercontent.com/20485546/98978429-f4521f00-24e7-11eb-803e-9e3d8cc34386.png)

**Comment by mulderphilip** [comment]
Thanks @Lyetenth , working great now!
