### ISSUE TITLE
Input txt file issue

### ISSUE THREAD

**Issue by ShannonK95** [FirstStreet/fsf_api_access_python#39]
Ticket [#1294](https://floodfactor.zendesk.com/agent/tickets/1294) submitted by Liao, Yanjun on 10/06 at 10:26pm

Hi,

I am a Flood Lab researcher and I encountered some problems pulling data through the API. This is likely a misunderstanding on my end and I am hoping you can help me figure out my mistake. Below is a description of the issue:

I am using a Python script (ScreenShot 1) with a list of FSIDs in a .txt file (ScreenShot2.png). The .txt file is located in the same folder as the python script as well as the virtual environment (ScreenShot3.png). However, when I run the python script, I got an error message that reads (ScreenShot4.png):

“firststreet.errors.InvalidArgument: File provided is not a valid file. Please check the file name. '.trial_fsid.txt'

In addition, I am pretty sure the virtual environment is activated correctly because I can run scripts that pull data for FSID input directly from the script.

What could potentially cause this? Any help would be appreciated.

Best,
Penny
-- 
Yanjun (Penny) Liao, PhD
Postdoctoral Research Fellow, Wharton Risk Center
The Wharton School, University of Pennsylvania
www.yanjunliao.com

<img width="631" alt="ScreenShot1" src="https://user-images.githubusercontent.com/59022592/101368051-b0e39a00-3874-11eb-9c57-3c93428019f6.png">

<img width="655" alt="ScreenShot2" src="https://user-images.githubusercontent.com/59022592/101368058-b3de8a80-3874-11eb-85cb-9c6bd3a4d27f.png">

<img width="336" alt="ScreenShot3" src="https://user-images.githubusercontent.com/59022592/101368066-b6d97b00-3874-11eb-803a-80f107d8face.png">

<img width="900" alt="ScreenShot4" src="https://user-images.githubusercontent.com/59022592/101368074-b93bd500-3874-11eb-8a46-cee10229003c.png">

**Comment by yjpenny** [comment]
Here's the output of running pip list in the same virtual environment I run my script in. 

[pip_list.txt](https://github.com/FirstStreet/fsf_api_access_python/files/5668283/pip_list.txt)

**Comment by Lyetenth** [comment]
Hey @yjpenny,

Thanks for posting that. I notice that your library is a bit outdated. (version 1.1.2)


Would you be able to update to the latest version?

```
cd /path/to/project

.\venv\Scripts\activate

pip install --upgrade fsf_api_access_python
```

I've been trying to figure out what's causing that bug, and I haven't been able to pin it down yet. Let's see if just updating will fix it

**Comment by yjpenny** [comment]
> Hey @yjpenny,
> 
> Thanks for posting that. I notice that your library is a bit outdated. (version 1.1.2)
> 
> Would you be able to update to the latest version?
> 
> ```
> cd /path/to/project
> 
> .\venv\Scripts\activate
> 
> pip install --upgrade fsf_api_access_python
> ```
> 
> I've been trying to figure out what's causing that bug, and I haven't been able to pin it down yet. Let's see if just updating will fix it

It works just fine after upgrading. Thank you so much!

**Comment by Lyetenth** [comment]
Good to hear! Feel free to post any other issues here as well
