### ISSUE TITLE
Invalid FSIDs?

### ISSUE THREAD

**Issue by yjpenny** [FirstStreet/fsf_api_access_python#40]
Hi there,

I am currently encountering an issue with my input FSIDs mostly returned as invalid. I first queried using census tract IDs in the following function (my understanding is that census tracts are identified by their original 11-digit number in the API?):
fs.probability.get_count(fsids, "tract", csv = True)
I am able to pull data for census tracts in DC but not any of the other states I have tried. All observations returned with the invalid ID flag. 

I then tried querying individual FSIDs from the examples on your README page and those failed as well (for example, 362493883). My connection setup is (rate_limit = 4950, rate_period = 60, connection_limit = 1000), and I've also tried lowering the rate_limit to 1000. 

Best,
Penny

**Question, Concerns, or Bugs:**
Questions regarding the only the First Street Foundation API 
(https://docs.firststreet.dev/docs/getting-started)

Any questions about this GitHub project, please use the `API Access Python Questions / Concerns` Issue Report

**Screenshots:**
If applicable, add screenshots to help explain your problem. Drag and drop images to the box below.

**Comment by Lyetenth** [comment]
Hey @yjpenny,

Are you using a file as an input to the function? If so, could you drop a copy here and I can try running it to see if it might be the file: https://drive.google.com/drive/folders/1WQIR70EwfukA4Xb_n6UATpK5W8dnb5Lx?usp=sharing

You are correct that the 11-digit numbers are tracts. For example, `[39061007100, 39153531702]` are two tract FSIDs

For the FSID from the readme `362493883`, that's a property FSID. As a result, running `probability.get_count` will return an `invalid_fsid` flag. You can try the two tract FSIDs from above to see if they work, they are both in Ohio

**Comment by yjpenny** [comment]
Yes, I overlooked the property/tract distinction in my attempt to query the sample FSIDs. The examples you gave do work for me. I am starting to wonder if this is related to states with single-digit FIPS codes because those are the ones that failed. I just dropped the file for Alabama in the Google Drive folder you link to.

**Comment by Lyetenth** [comment]
Hey @yjpenny,

Looks like that was the issue. Stripping the leading 0's resulted in a successful pull. I've dropped the stripped FSID list to the same Google Drive folder (called `prop_geo_al_out_stripped.txt`) for your convenience

Try again with that file if you haven't already, and let me know how it goes

**Comment by yjpenny** [comment]
Yes, now it works. Thank you!
