### ISSUE TITLE
Basic access problems

### ISSUE THREAD

**Issue by DSNoonan** [FirstStreet/fsf_api_access_python#41]
I'm not having any success in accessing the data.  I followed the install steps, and it appeared to install fine.  But none of my commands can execute.  I tried to follow the example #6 [here](https://github.com/FirstStreet/fsf_api_access_python#examples) and wrote:
	`python -m firststreet -p probability.get_depth -i 390000227`
I get this response in PowerShell:

> usage: __main__.py [-h] -p PRODUCT [-api_key API_KEY] [-v VERSION] [-log LOG] [-connection_limit CONNECTION_LIMIT]
>                    [-rate_limit RATE_LIMIT] [-rate_period RATE_PERIOD] [-o OUTPUT_DIR] [-s SEARCH_ITEMS]
>                    [-l LOCATION_TYPE] [-y YEAR] [-rp RETURN_PERIOD] [-eid EVENT_ID] [-f FILE] [-e EXTRA_PARAM]
> __main__.py: error: unrecognized arguments: -i 390000227
> 

For what it's worth, when I try that same command-line code with "-s" substituted in for "-i", then the output ends with:

> firststreet.errors.UnknownError: Network Error 403: The user has no policy access to service probability

I'm running python v3.8.6 on a Windows 7 Pro desktop.

Thanks!
-Doug

**Question, Concerns, or Bugs:**
Questions regarding the only the First Street Foundation API 
(https://docs.firststreet.dev/docs/getting-started)

Any questions about this GitHub project, please use the `API Access Python Questions / Concerns` Issue Report

**Screenshots:**
If applicable, add screenshots to help explain your problem. Drag and drop images to the box below.

**Comment by Lyetenth** [comment]
Hi Doug,

It looks like the README on the front page is a outdated, Please see the [wiki pages here](https://github.com/FirstStreet/fsf_api_access_python/wiki) for the updated info. Sorry about that!

For the issue regarding the `The user has no policy access to service probability`, it looks like there was a slight issue with setting the policy for your account initially. We've updated it, and you should be good to go now. Can you try again and see how it goes?

Let me know if there's any other issues that happen,

**Comment by DSNoonan** [comment]
Thank you for the quick and helpful response.  It looks like everything went through just fine now.  Much appreciated!
Happy holidays,
-Doug
