### ISSUE TITLE
Mac installation: "activate" script and Shapely error

### ISSUE THREAD

**Issue by Steve-Koller** [FirstStreet/fsf_api_access_python#43]
Hi all, thank you for making these data accessible through the API! It's deeply appreciated. I just installed the project on my Mac and wanted to share my experience in case it might be helpful to others, or might justify updating the Wiki. Had to tweak a few things to successfully install. Apologies if this isn't the right place to raise this issue; I'm still pretty new to GitHub. 

For starters, I am using macOS Catalina 10.15.7 and Python 3.9.1.

I followed the Wiki Mac installation instructions verbatim, and ran into the first issue with `.\venv\Scripts\activate` which returned "command not found" in Terminal.

After looking around online (link below), I found `source venv/bin/activate` successfully activated my venv folder.

The second issue came when running `pip install fsf-api-access-python`. It returned this error message: 

> ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1m/11lx175j7_953x41kstp2s9w0000gn/T/pip-install-_yk62ho1/shapely_477be29c282646879950ef9ff1c53778/setup.py'"'"'; __file__='"'"'/private/var/folders/1m/11lx175j7_953x41kstp2s9w0000gn/T/pip-install-_yk62ho1/shapely_477be29c282646879950ef9ff1c53778/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/1m/11lx175j7_953x41kstp2s9w0000gn/T/pip-pip-egg-info-re7un7pc
         cwd: /private/var/folders/1m/11lx175j7_953x41kstp2s9w0000gn/T/pip-install-_yk62ho1/shapely_477be29c282646879950ef9ff1c53778/
    Complete output (12 lines):
    Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
    Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
    Failed `CDLL(/usr/local/lib/libgeos_c.dylib)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1m/11lx175j7_953x41kstp2s9w0000gn/T/pip-install-_yk62ho1/shapely_477be29c282646879950ef9ff1c53778/setup.py", line 85, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/private/var/folders/1m/11lx175j7_953x41kstp2s9w0000gn/T/pip-install-_yk62ho1/shapely_477be29c282646879950ef9ff1c53778/shapely/_buildcfg.py", line 190, in <module>
        lgeos = load_dll('geos_c', fallbacks=alt_paths)
      File "/private/var/folders/1m/11lx175j7_953x41kstp2s9w0000gn/T/pip-install-_yk62ho1/shapely_477be29c282646879950ef9ff1c53778/shapely/_buildcfg.py", line 162, in load_dll
        raise OSError(
    OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Again, after looking around online (link below), it looks like this is a known issue (I believe with Python 3.9, but not 100% sure). The suggested workaround was to run `brew install geos` first, so I did. After that, `pip install fsf-api-access-python` worked like a charm.

**Sources:**
https://docs.python.org/3/library/venv.html
https://github.com/Toblerity/Shapely/issues/1040

**Comment by Lyetenth** [comment]
Hey @Steve-Koller,

Thanks for identifying the errors and the solutions. I've updated the wiki page for the OSX/Linux installation steps with the updated command and a notice for the Python 3.9 installation issue

Let me know if you see any other inconsistencies or inaccuracies

**Comment by Steve-Koller** [comment]
Thanks, @Lyetenth! Nothing else to report— things are running smoothly now.
