### ISSUE TITLE
Network Error 403: The user has no policy access to service adaptation

### ISSUE THREAD

**Issue by Steve-Koller** [FirstStreet/fsf_api_access_python#44]
Hi all, I believe I'm having a similar issue as Doug in #41. My setup with the virtual environment went fine, and I am running the below script in PyCharm (using my actual assigned API key) trying to pull from the adaptation product. I am running macOS Catalina 10.15.7 and Python 3.9.1.

**SCRIPT:**

`import requests`

`url = "https://api.firststreet.org/v1/apikey"`

`header = {
  "Authorization": "Bearer your-api-key"
}`

`r = requests.get(url, headers=header)`

`import firststreet`
`fs = firststreet.FirstStreet("api-key")`

`firststreet.FirstStreet(
    api-key,
    connection_limit=100,
    rate_limit=20000,
    rate_period=1,
    log=True
)`

`adaptation_summary = fs.adaptation.get_summary(search_items=[511447411, 511447412, 511447413], location_type="property", csv=True, output_dir='/output')`

**ERROR:**
After running above script, I receive the following error:

> firststreet.errors.UnknownError: Network Error 403: The user has no policy access to service adaptation

I'm not sure if this is a similar setup issue as in #41 or something different. Any guidance you can provide would be most appreciated. Thank you!

**Comment by Lyetenth** [comment]
Hey @Steve-Koller,

It looks like it was a similar issue. The key should now be updated and you should be able to access the correct services

Let me know if it still returns an error when you run a product

**Comment by Steve-Koller** [comment]
Hi @Lyetenth, thank you for looking into that. I'm not getting the error any more and have access now. Thanks again!
