### ISSUE TITLE
Rate Limit Error when pulling location summary data for properties

### ISSUE THREAD

**Issue by pranjalirai** [FirstStreet/fsf_api_access_python#47]
I am trying to pull location summaries for all properties in Snohomish County WA.
When running the code to pull data for all properties (261233 properties), I get the following rate limit error:

RateLimitError: Network Error 429: Rate limit exceeded. Limit: 5000. Remaining: 0. Reset: 52

I am only able to pull data for 4000 properties at a time. 

Is there a way I can lower the rate limit from my end so that I do not make more than 5000 pulls/ min?

**Comment by Lyetenth** [comment]
Hi Pranj,

Could you provide your Python version and the version of the `Fsf-api-access-python` library? The latter can be found by running `pip list` in a terminal and looking for the `Fsf` library in the list.

**Comment by pranjalirai** [comment]
I have `fsf-api-access-python` version 2.2.4, and Python version 3.8.5

**Comment by Lyetenth** [comment]
Hi Pranj,

You can add a rate_limit and rate_period to the initialization line like:

`fs = firststreet.FirstStreet(api_key, rate_period=60, rate_limit=5000)`

The example above sets it to pull 5000 properties every 60 seconds. Note that if you use the csv=True, it may take some time to generate the CSV file since there are quite a lot of properties

Let me know if there are any additional issues

**Comment by pranjalirai** [comment]
Thanks, that worked like a charm!

**Comment by rcoskrey** [comment]
I'm having a similar issue that was not solved by the rate_limit and rate_period additions. I'm working with a dataset of about 700,000 FSIDs, and trying to get location summary/location detail/etc. for each of them. I tried setting rate_period to 60 and rate_limit to 5000 and running a subset of around 100k properties through the location_get summary. As soon as it reaches 4900/100000 properties, the code fails and I get a "rate limit error" message. Is there a way to avoid this beyond changing the rate_period to 60 and rate_limit to 5000? I've tried playing around with it, but it fails every time.

**Comment by Lyetenth** [comment]
Hey @rcoskrey,

Are you seeing a lot of errors during the pull like `Timeout Errors` beside the progress bar? Or no errors (other than the rate limit one)? 

Also when you tried adjusting the rate_limit to a lower value, what did you adjust it to? If it's stopping at 4900, then (hypothetically) setting it to 4899 should reduce it enough to not have the `rate limit error` (just temporarily to test the issue).

You can also try adjusting the `connection_limit` parameter to a smaller value. It defaults to 100, so try something like 75 or 50. The `connection_limit` parameter changes the number of simultaneous connections.

Last questions:
- What's your current version of the library? The current version is `2.3.2`, if your version is a bit far behind, then the performance changes may not have been applied
- Who is your API key registered under, and which team/organization/academic institution are you a part of? We can take a look on our end to see if the API key is set correctly

**Comment by rcoskrey** [comment]
I'm only seeing Rate Limit Error, no Timeout Errors along the progress bar. Once it stops running, and I scroll through all of the error lines, I also see "Runtime Error: Session is Closed" and "ERROR Task exception was never received"

I tried setting rate_limit to 4000 and keeping rate_period at 60, but it still stopped at 4950 and threw the "Rate Limit Error". I also changed the connection limit to 50 but got the same outcome. When I changed the connection limit to 200, I got to around 7500/100000 but still got the Rate Limit Error then. 

I also tried upgrading my library to 2.3.2 to see if that would fix it (it was 2.2.5 before). However, it still threw Rate Limit Error at around 4950/100000 properties. 

My API key is registered under Laura Bakkensen, and the institutions of our team are University of Arizona and Federal Reserve Bank of Richmond.

If I can provide any other information that would be helpful in troubleshooting this, please let me know. I can share the code/response I'm getting when the error appears.

**Comment by Lyetenth** [comment]
Hi @rcoskrey,

I've taken a look at the API key and it looks like it's set correctly, which rules out that as the error.

I'm going to move this discussion to a new issue since it seems to be different from the one that pranj has. I'll tag you in the new issue discussion.
