### ISSUE TITLE
Command line issue 

### ISSUE THREAD

**Issue by psunecon2017** [FirstStreet/fsf_api_access_python#51]
My computer is a mac. When I only grab info for one record via the command line, it works well. But if I want to do it for multiple records, errors occurred. 
For example, if typing "python -m firststreet -p location.get_detail -s 39061007100;39153531702 -l tract", then 
"
Traceback (most recent call last):
  File "/Users/psun/miniconda3/envs/python3env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/psun/miniconda3/envs/python3env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/psun/miniconda3/envs/python3env/lib/python3.9/site-packages/firststreet/__main__.py", line 163, in <module>
    fs.location.get_detail(search_items,
  File "/Users/psun/miniconda3/envs/python3env/lib/python3.9/site-packages/firststreet/api/location.py", line 44, in get_detail
    raise InvalidArgument("No loocation type provided: {}".format(location_type))
firststreet.errors.InvalidArgument: No loocation type provided: None
zsh: command not found: 39153531702
"
A similar issue happened when I tried to get the tile file. When I ran "python -m firststreet -p tile.get_probability_depth -s (12,932,1715);(12,942,1715) -y 2020 -rp 5", I received "zsh: parse error near `-y'". 

Could you help me figure out what happened? 

The following are those packages I installed 

aiohttp                   3.7.4.post0              pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
asyncio-throttle          1.0.1                    pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
blas                      1.0                    openblas  
ca-certificates           2021.1.19            hecd8cb5_1  
certifi                   2020.12.5        py39hecd8cb5_0  
chardet                   4.0.0                    pypi_0    pypi
fsf-api-access-python     2.3.2                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
libcxx                    10.0.0                        1  
libffi                    3.3                  hb1e8313_2  
libgfortran               3.0.1                h93005f0_2  
libopenblas               0.3.10               h0794777_0  
multidict                 5.1.0                    pypi_0    pypi
ncurses                   6.2                  h0a44026_1  
nest-asyncio              1.5.1                    pypi_0    pypi
numpy                     1.19.2           py39h0fa1045_0  
numpy-base                1.19.2           py39h3a452eb_0  
openssl                   1.1.1j               h9ed2024_0  
pandas                    1.2.3            py39hb2f4e1b_0  
pip                       21.0.1           py39hecd8cb5_0  
python                    3.9.2                h88f2d9e_0  
python-dateutil           2.8.1              pyhd3eb1b0_0  
pytz                      2021.1             pyhd3eb1b0_0  
readline                  8.1                  h9ed2024_0  
requests                  2.25.1                   pypi_0    pypi
setuptools                52.0.0           py39hecd8cb5_0  
shapely                   1.7.1                    pypi_0    pypi
six                       1.15.0           py39hecd8cb5_0  
sqlite                    3.35.1               hce871da_0  
tk                        8.6.10               hb0a8c7a_0  
tqdm                      4.59.0                   pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
tzdata                    2020f                h52ac0ba_0  
urllib3                   1.26.4                   pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h1de35cc_0  
yarl                      1.6.3                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3

**Comment by Lyetenth** [comment]
Hi @psunecon2017,

Looks like the arguments might be parsed a bit differently in a Mac terminal. Try this:

`python -m firststreet -p location.get_detail -s "39061007100;39153531702" -l tract`


ie: Try adding a double quote around the search item list. Let me know if this fixes the error

**Comment by psunecon2017** [comment]
It works perfectly. Thanks a lot.
