### ISSUE TITLE
Access Issue - "Network Error 403: The user has no policy access to service economic"

### ISSUE THREAD

**Issue by mulderphilip** [FirstStreet/fsf_api_access_python#53]
I updated the FSF package today to start working with the newly released data. When I tried to access the Average Annualized Loss product, I got the error referenced in the title. Perhaps relatedly, when I use the property location detail product, I don't see any of the new fields referenced in the Data Dictionary (i.e. floorElevation, building, floodType, or residential). 

I saw two related questions earlier where the problem ended up being the accounts access setting; maybe my issue is similar. Thank you for your help!

**System details** 
Python: 3.7, running in Jupyter Notebook on Windows 
fsf-api-access-python version 2.3.2 

**AAL error** 
fs = firststreet.FirstStreet("API KEY",rate_limit=5000,rate_period=62, connection_limit=100)
aal = fs.aal.get_summary(search_items=[511447411, 80000002], location_type="property", csv=True)

**Location detail product missing new fields**
pull_fsid = [421060881]
fs.location.get_detail(pull_fsid,'property',csv=True)

**Comment by brett-l** [comment]
Hi Phillip, your permissions are updated and you should have access now.

**Comment by mulderphilip** [comment]
Thank you! The AAL does seem to be working now, but I'm still not seeing the new location detail fields. Do you think that's a separate issue?

**Comment by Lyetenth** [comment]
Hi Philip,

Yes, that's a separate issue. We're finishing up the QA on the location product but the release should be done sometime this week.

I'll drop a message here when it's up

**Comment by Lyetenth** [comment]
Hi @mulderphilip,

Version 2.3.4. is up now with the new location detail fields (floorElevation, basement, units, stories, floodType, residential)

Do an upgrade and let me know if you find any issues

**Comment by mulderphilip** [comment]
@Lyetenth Thanks for the update! Will let you know

**Comment by mulderphilip** [comment]
@Lyetenth Everything is working great, thanks as always for the fix
