### ISSUE TITLE
Frequent Disruption in API Access

### ISSUE THREAD

**Issue by psunecon2017** [FirstStreet/fsf_api_access_python#54]
**Question:**
When I grab the property-level data using FSF API, the work is often suddenly terminated so that I had to spend lots of time restarting the same process. Here is the sample code. 
`fs=firststreet.FirstStreet("key", connection_limit=100, rate_limit=5000, rate_period=60)`
`probability_depth = fs.probability.get_chance(search_items="fsid_prop_tx1.txt", csv=True)
`
The text file includes 500,000 FSIDs. The error is pasted at the screenshots part. I was wondering whether it's because I process too many FSIDs for one shot. Is there anyway I can do to make the access move smoothly while being able to process such a number of FSIDs one time? Thanks!

**Additional Information:**
Python Version: 3.9

OS: Mac

Fsf-api-access-python Version: The Default version 

**Screenshots:**
`
return await self.product_response(response, endpoint)
  File "...python3env/lib/python3.9/site-packages/firststreet/http_util.py", line 166, in product_response
    raise self._network_error(self.options, rate_limit, error=body.get('error'))
firststreet.errors.RateLimitError: Network Error 429: Rate limit exceeded. Limit: 5000. Remaining: 0. Reset: 1
`

**Comment by mulderphilip** [comment]
@psunecon2017 I've had success limiting this problem by bumping the rate period up a hair to 62. So: 

rate_limit=5000,rate_period=62, connection_limit=100

For whatever reason, the API needs a little buffer room to not run over the rate limit.

**Comment by psunecon2017** [comment]
Gotcha. Thanks a lot. I will try this.
