### ISSUE TITLE
AAL extra parameters with multiple search items

### ISSUE THREAD

**Issue by mulderphilip** [FirstStreet/fsf_api_access_python#55]
Reading through the AAL calculator documentation, it looks like inputting extra parameters (e.g. a custom first floor elevation) can only be done through the command line on an item-by-item basis. As an extra feature, it would be very helpful to be able to pass a vector of extra parameters alongside a vector of search items when pulling data from a python file across many FSIDs. 

Happy to clarify, and thank you as always for all the great API features and support!

**Comment by Lyetenth** [comment]
Hi @mulderphilip,

Yes, that's one of the features I thought about as well when updating the library but didn't have time to implement.

I have this on the backlog, but it might be a while before I can get to it

**Comment by mulderphilip** [comment]
Glad to hear it, totally understand you have a lot on your plate!
