### ISSUE TITLE
Property Values used in AAL calculator

### ISSUE THREAD

**Issue by mulderphilip** [FirstStreet/fsf_api_access_python#58]
Are the property values returned by the API an estimate of the total property's market value (the amount it would likely sell for) or the physical structure's replacement value (the cost of rebuilding the home to its current condition). I.e., is it the value of the full property including land, or just the value of the physical structure?

My understanding is that the USACE depth-damage curves used by the FSF model are expressed as percentages of a home's replacement value. Does the AAL output multiply the depth-damage curves for each property by its full value or replacement value? 

Happy to clarify further, and thank you as always.

**Comment by Lyetenth** [comment]
Hey @mulderphilip,

The property values in the AAL product are estimates on the physical structure. Specifically, it is the % damage from the USACE damage curves, applied to building structure value

Let me know if you have any other questions

**Comment by mulderphilip** [comment]
Thank you @Lyetenth. Related, are the AVM also the physical structure values, or are they modified when they are run through the AAL calculator?

**Comment by Lyetenth** [comment]
The AVM values are not the structure values, they are the actual property value that we produced as part of this analysis: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3767128

**Comment by mulderphilip** [comment]
Thank you again @Lyetenth, I think I have a good understanding of this variable now.
