### ISSUE TITLE
List of all city FSID/FIPS

### ISSUE THREAD

**Issue by rht** [FirstStreet/fsf_api_access_python#60]
Basically #56, but for city instead. I have been using search engine to find if such public data can be found in any gov websites. But can't find any so far.

**Comment by Lyetenth** [comment]
Hi @rht,

When you get the chance, can you email Brett? He can get you a list of city FSIDs

**Comment by rht** [comment]
Ah, right. I have access to csvs now. About few hundred of MB per state. Do you think the wiki should contain this information on who to ask for the city FSIDs?

**Comment by rht** [comment]
I have another concern: the csvs provided by Brett are not compressed, and so generally take much longer to download. Don't you think it is better to compress them to speed up download and to save disk space that is usually rented from AWS or Digital Ocean?
