### ISSUE TITLE
Command Line Issue

### ISSUE THREAD

**Issue by psunecon2017** [FirstStreet/fsf_api_access_python#66]
**Question:**
When I use the command line codes to extract data, although I specified connection limit, rate limit, rate period, such as 
`python -m firststreet -connection_limit 100 -rate_limit 2000 -rate_period 62 -p fema.get_nfip -s "19153004900;39153531702" -l tract`, I was always asked whether I need to adjust the connection parameters, saying "Adjust connection parameters (Y/N)? Defaults to 100 connections, with a rate limit of 5000 calls per 60 seconds:". This is a little annoying. How could I fix it? Thanks. 

**Additional Information:**
Python Version: 3.9.2

OS: Mac

Fsf-api-access-python Version: 2.3.5

**Screenshots:**
Not applicable

**Comment by Lyetenth** [comment]
Hi @psunecon2017,

Looks like there was a bug and it still asked for rate limit values even with the flags provided. I just pushed an update (2.3.6) that should fix that issue so it doesn't ask for values when you run `python -m firststreet -connection_limit 100 -rate_limit 2000 -rate_period 62 -p fema.get_nfip -s "19153004900;39153531702" -l tract`

Note that there's another prompt afterwards to add an output directory. You can hide that prompt as well by including `-o OUTPUT_DIRECTORY_PATH". Ex: `python -m firststreet -connection_limit 100 -rate_limit 2000 -rate_period 62 -p fema.get_nfip -s "19153004900;39153531702" -l tract -o output`

Update the library, and let me know if there's any other bugs

**Comment by psunecon2017** [comment]
It works well now. Thank you.
