### ISSUE TITLE
Location Summary 'PropertyCount' Definition

### ISSUE THREAD

**Issue by mulderphilip** [FirstStreet/fsf_api_access_python#67]
Hello, 

I have a question on the definition of the 'PropertyCount' variable returned by non-property Location Summary queries. Does the count include all properties in the geography, or just residential properties? If only residential properties, does it include single family homes and/or condos and/or multifamily apartments? 

Follow-up question: Which property types are included in the calculation of Annual Loss Area counts and total losses? 

Thank you!

**Comment by Lyetenth** [comment]
Hi @mulderphilip,

The `PropertyCount` variable in the Location Summary includes all properties (residential and commercial) for all units

For the Average Annual Loss, only residential properties with 1-4 units are included

**Comment by mulderphilip** [comment]
Hi @Lyetenth, thanks for the response. 

Do you know if any of the products return the count of residential properties with 1-4 units? I don't see anything, but maybe I've missed something.

**Comment by Lyetenth** [comment]
Hi @mulderphilip,

We don't have a product that pulls the counts for residential 1-4, but I pulled the counts for the zcta (residential 1-4) into an excel file. Let me know if this works

[zcta_property_count.xlsx](https://github.com/FirstStreet/fsf_api_access_python/files/6688236/zcta_property_count.xlsx)

**Comment by mulderphilip** [comment]
That looks like exactly what we need. Thank you as always for your speedy help!
