### ISSUE TITLE
Network Error 403: The user has no policy access to service location.

### ISSUE THREAD

**Issue by utkarsh-gangwal** [FirstStreet/fsf_api_access_python#72]
Hello! I am facing a similar issue as #44 and #41. A few weeks ago, I ran the code below and I was able to get the output as a CSV file. However, when I tried running the same code now, it kept on giving the following error: "Network Error 403: The user has no policy access to service location." I am running the code by calling the python script (written in sublime) in the command prompt. The virtual environment set-up where I installed the 'fsf-api-access-python' went fine for me.

**Code:**
`import firststreet`

`api_key = 'My API key'`
`fs = firststreet.FirstStreet(api_key, connection_limit=100, rate_limit=20000, rate_period=1, log=True)`

`location_summary = fs.location.get_summary(search_items=[511447411, 511447412, 511447413], location_type="property", csv=True)`

I am running python version: 3.9.7 on a windows 10 desktop.

Thanks!
Utkarsh

**Screenshots:**
![cmd_prompt_error](https://user-images.githubusercontent.com/73367125/146255822-6bef507b-a8a7-4415-a0fe-53ee83121b67.PNG)

**Comment by Lyetenth** [comment]
Hi @utkarsh4499,

There should have been an email sent out earlier about the API, please contact us through email

Thanks,
Kelvin

**Comment by Lyetenth** [comment]
Issue resolved, closing

**Comment by ghost** [comment]
I also had a similar issue:

UnknownError: Network Error 403: The user has no policy access to the service location. ('https://api.firststreet.org/v1/location/summary/property?address=300 River Park Drive, Mankato, MN, 56001&', '300 River Park Drive, Mankato, MN, 56001', 'location', 'summary')

I am using my supervisor's API key. Could you please let us know how to solve this issue? Thank you!

**Comment by utkarsh-gangwal** [comment]
Hi! Send an email to FSFL asking for the data you need.

**Comment by ghost** [comment]
Hi, thanks for your reply. Does it mean that we cannot get the data through the API and have to request data using email? Thanks.

**Comment by utkarsh-gangwal** [comment]
Yes.
