### ISSUE TITLE
Requesting tile maps using REST API

### ISSUE THREAD

**Issue by pranjalirai** [FirstStreet/fsf_api_access_python#8]
I have been trying to request map tiles using the url and api key. My python script is based on the earlier API documentation provided on your website for requesting map tiles. After your recent updates, I have been unable to request tiles. Following is the error for url= "https://api.firststreet.org/v1/tiles/probability/2020/100/17/30990/54379/.png":
<Response [501]>
b'{"error":{"code":"501","message":"Invalid service, check URL"}}'

I wanted to ask if the REST API for first street map tiles is still available. If yes, can you provide a  python script example for requesting map tiles.

**Comment by Lyetenth** [comment]
Hey Pranj,

It looks like the documentation is outed on that page. 

Try this example:
`https://api.firststreet.org/v1/tile/probability/depth/2020/5/12/942/1715.png`



The pattern for probability depth:
`https://api.firststreet.org/v1/tile/probability/depth/{year}/{returnPeriod}/{z}/{x}/{y}.png`

The pattern for historic event:
`https://api.firststreet.org/v1/tile/historic/event/{eventId}/{z}/{x}/{y}.png`

**Comment by pranjalirai** [comment]
Thanks, I am able to request tiles for that link.
