### ISSUE TITLE
Error while importing fsf-api-access package

### ISSUE THREAD

**Issue by pranjalirai** [FirstStreet/fsf_api_access_python#9]
After creating a new virtual environment, and installing fsf-api-access package using pip, I am unable to successfully import the package using python. Following is the error I receive:
![image](https://user-images.githubusercontent.com/57599303/88084936-f576cf00-cb39-11ea-8506-3146d848ee26.png)

It seems that there is an issue with importing shapely through fsf-api-access package installed through pip. Can you provide the conda install documentation for fsf-api-access package?

**Comment by Lyetenth** [comment]
Hey Pranj, what version is your Python? And are you on a Windows?

It looks like for `Windows` + `Python 2.7` combination, binary wheels aren't available. https://gis.stackexchange.com/questions/62925/shapely-not-installing-correctly

If you have Python 3, you can also try to install shapely manually with `pip install shapely` 
The linked post also suggests `conda install shapely` if you are using `Anaconda` or `Miniconda`

**Comment by pranjalirai** [comment]
That works. 
I am now able to import fsf-api-access package.
Thanks
